env:
  es2021: true
extends:
  - 'plugin:react/recommended'
  - google
  - 'plugin:@typescript-eslint/recommended' # <-- TypeScript推奨ルールを追加
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  # 関数の複雑さを 10 以下にする
  complexity: ['error', 10]
  # React のプロパティの型チェックを省略する (TypeScript でチェックされるため)
  react/prop-types: off
  # インターフェースの先頭文字を "I" にする
  #'@typescript-eslint/interface-name-prefix':
  #  - error
  #  - prefixWithI: 'always'
